# Generated by Django 5.2.6 on 2025-09-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_item_views_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('jersey', 'Jersey'), ('shoes', 'Football Shoes'), ('ball', 'Football'), ('equipment', 'Training Equipment'), ('accessories', 'Accessories'), ('merchandise', 'Merchandise')], max_length=20),
        ),
    ]
