# Generated by Django 5.2.6 on 2025-09-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
